excel:
  prefix:
    staffCode: PH39028
    name: Vu Duc Phan
    accountFPT: phanvdph39028@fpt.edu.vn
    accountFE: phanvdph39028@fe.edu.vn
    contentType: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    historyImport: import-history.txt
app:
  verify:
    user: phan
    type: 0
    key: Tm9uZyBIb2FuZyBWdQ==
spring:
  datasource:
    url: jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=exam_distribution_test
    username: sa
    password: 123
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
